# cf. https://docs.traefik.io/providers/docker/#provider-configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    defaultRule: 'Host(`{{ index .Labels "traefik.host" }}.localhost`)'
serversTransport:
  maxIdleConnsPerHost: 1000

entryPoints:
  web:
    # Listen on port 8081 for incoming requests
    address: ":80" # same as ":8888/tcp"
api:
  insecure: true
