# cf. https://docs.traefik.io/providers/docker/#provider-configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
serversTransport:
  maxIdleConnsPerHost: 1000

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  fastapi:
    address: ":9292"
api:
  insecure: true
